# Dependencies
markdown:       kramdown

# Site settings
title:          Swabha
email:          myfirstname @ cs.cmu.edu
description:    PhD student at Carnegie Mellon University, research interests include predicate-argument semantics and multi-task learning for natural language processing.

baseurl:        ""
url:            "http://swabhs.github.io" 

twitter_username: swabhz
github_username:  swabhs

# Custom vars
github:
  repo:         https://github.com/swabhs
  
permalink:      pretty
theme:          jekyll-theme-tactile
