# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.

# Site settings
title: Swabha's blog
email: <my first name> @ cs.cmu.edu
description: > # this means to ignore newlines until "baseurl:"
    I am a PhD student at the Carnegie Mellon School of Computer Science. I work on Natural Language Processing. Learning and inference for structured objects fascinates me, especially if the structures deal with semantic formalisms. I created this site to ramble about things I'm reading and learning about, because human memory is limited...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: swabzzzz
github_username:  swabhs

# Build settings
markdown: kramdown
